name: Frontend CI (Docker Build)

on:
  push:
    branches:
      - frontend 
    paths:
      - 'frontend/**' 
  pull_request:
    branches:
      - frontend
    paths:
      - 'frontend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          cd frontend
          docker build -t my-next-app:latest .
